- .travis.yml
- CMakeLists.txt
- pmdk-convert.c
- pmemobj_convert_1.1_to_1.2.c
- pmemobj_convert_1.2_to_1.3.c
- tests/basic.cmake
- travis.yml
- utils/check_license/check-headers.sh
- utils/check_license/check-license.c
- utils/check_license/file-exceptions.sh
- utils/check_whitespace
- utils/cstyle
- utils/docker/build.sh
- utils/docker/images/Dockerfile.fedora-28
- utils/docker/images/Dockerfile.ubuntu-18.04
- utils/docker/images/build-image.sh
- utils/docker/images/download-pmdk.sh
- utils/docker/images/push-image.sh
- utils/docker/pull-or-rebuild-image.sh
- utils/docker/run-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/4)
> cstyle, check-license, check-whitespace & Travis integration

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/5)
> Add Travis badge to main README.

- codecov.yml
- travis.yml
- utils/docker/build.sh
- utils/docker/images/Dockerfile.ubuntu-18.04
- utils/docker/run-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/6)
> add coverage support

- CMakeLists.txt
- tests/CMakeLists.txt
- tests/transaction.c
- tests/transactions_single_file_pools.cmake
- tests/trip_on_post_commit.gdb
- tests/trip_on_pre_commit.gdb
- utils/docker/run-build.sh
- utils/utils.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/9)
> Test for pmempool convert

- tests/CMakeLists.txt
- tests/clean.c
- tests/helpers.cmake
- tests/skip_test.cmake
- tests/tx_intr_multi_file_poolsets_devdax.cmake
- tests/tx_intr_poolsets_with_local_replica_devdax.cmake
- tests/tx_intr_single_file_pools_devdax.cmake
- tests/tx_intr_single_file_poolsets_devdax.cmake
- utils/docker/images/download-pmdk.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/11)
> Add tests for pmdk-convert on Device DAX

- tests/CMakeLists.txt
- tests/clean.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/13)
> test: fix build with libpmempool

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/16)
> add appveyor badge

- pmdk-convert.c
- tests/CMakeLists.txt
- tests/remote.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/14)
> add remote replica detection

- index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/20)
> doc: fix path to man html

- doc/pmdk-convert/pmdk-convert.1.md
- travis.yml
- utils/docker/build.sh
- utils/docker/run-build.sh
- utils/docker/run-doc-update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/15)
> doc: add pmdk-convert manpage

- utils/docker/run-build.sh
- utils/docker/run-doc-update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/22)
> doc: fix path to cmake file

- utils/docker/images/Dockerfile.fedora-28
- utils/docker/run-doc-update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/24)
> doc: fix hub dependency and web_manpages path

- doc/pmdk-convert/pmdk-convert.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/21)
> doc: doc autogen test

- doc/pmdk-convert/pmdk-convert.1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/27)
> add convert manpage

- ChangeLog
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/35)
> Add 1.5 change log.

- index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/37)
> doc: fix link to manpage in index.html

- utils/docker/run-doc-update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/45)
> doc: fix path in auto docs update

- pmdk-convert.c
- tests/cli.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/40)
> Add test cases to cli_test and fix execution of pmdk-convert for empty stdin

- travis.yml
- utils/docker/build.sh
- utils/docker/run-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/46)
> common: split jobs on travis into two builds: debug and release

- tests/CMakeLists.txt
- tests/tx_intr_pool_devdax.cmake
- tests/tx_intr_poolset_local_2devdaxes.cmake
- tests/tx_intr_poolset_local_2devdaxes_rep_2regfiles.cmake
- tests/tx_intr_poolset_local_2regfiles.cmake
- tests/tx_intr_poolset_local_2regfiles_rep_2devdaxes.cmake
- tests/tx_intr_poolset_local_2regfiles_rep_3regfiles.cmake
- tests/tx_intr_poolset_local_devdax.cmake
- tests/tx_intr_poolset_local_devdax_rep_devdax.cmake
- tests/tx_intr_poolset_local_regfile.cmake
- tests/tx_intr_poolset_local_regfile_rep_regfile.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/43)
> tests: add new tests with interrupted transactions

- tests/CMakeLists.txt
- tests/compare_replicas.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/38)
> Add pmempool and test which compares replicas after pool conversion

- pmdk-convert.c
- tests/remote.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/48)
> remote poolset should be detected before layout detection

- tests/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/47)
> tests: add pmemspoil to cmake

- utils/docker/build.sh
- utils/docker/images/Dockerfile.fedora-28
- utils/docker/images/Dockerfile.ubuntu-18.04
- utils/docker/images/build-image.sh
- utils/docker/pull-or-rebuild-image.sh
- utils/docker/run-build.sh
Fix for few badly copy-pasted descriptions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/50)
> common: fix descriptions in dockers

- pmdk-convert.c
- pmemobj_convert.h
- pmemobj_convert_v1.c
- pmemobj_convert_v2.c
- pmemobj_convert_v3.c
- pmemobj_convert_v4.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/54)
>  Make sure there are no buffer overflows in path/error string construction

- pmdk-convert.c
- pmemobj_convert_v3.c
- pmemobj_convert_v4.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/57)
> fix static analyzer issues

- CMakeLists.txt
- tests/CMakeLists.txt
- tests/tx_intr_pool_devdax.cmake
- tests/tx_intr_poolset_local_2devdaxes.cmake
- tests/tx_intr_poolset_local_2devdaxes_rep_2regfiles.cmake
- tests/tx_intr_poolset_local_2regfiles.cmake
- tests/tx_intr_poolset_local_2regfiles_rep_2devdaxes.cmake
- tests/tx_intr_poolset_local_2regfiles_rep_3regfiles.cmake
- tests/tx_intr_poolset_local_devdax.cmake
- tests/tx_intr_poolset_local_devdax_rep_devdax.cmake
- tests/tx_intr_poolset_local_regfile.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/59)
> Fix detection and remove whitespaces

- travis.yml
- utils/docker/build.sh
- utils/docker/run-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/60)
> common: split travis jobs to reduce exec time

- CMakeLists.txt
- appveyor.yml
- tests/CMakeLists.txt
- tests/helpers.cmake
- tests/transaction.c
- tests/tx_intr_pool_regfile.cmake
- tests/tx_intr_poolset_local_2regfiles.cmake
- tests/tx_intr_poolset_local_regfile.cmake
- tests/tx_intr_poolset_local_regfile_rep_regfile.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/52)
> Implementing tests for interrupted tranasactions for Windows

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/62)
> doc: fix link in README file

- utils/check_license/check-license.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/64)
> common: update check-licence to the newest one from PMDK

- pmdk-convert.c
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/65)
> fix typo in usage

- tests/CMakeLists.txt
- tests/spoiled_pool_hdr.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/49)
> tests: add pmempool convert with pmemspoil test

- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/71)
> Don't install pmdk on AppVeyor

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/70)
> Use PMDK with DDAX fixes from 1.2, 1.3, 1.4 and 1.5 branches.

- CMakeLists.txt
- tests/CMakeLists.txt
- tests/cli.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/72)
> Fix few bugs in tests

- CMakeLists.txt
- ChangeLog
- tests/cli.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/73)
> Merge stable-1.5 into master

- CMakeLists.txt
- ChangeLog
- tests/cli.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/74)
> Update PMDK to 1.6.1

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/76)
> Update PMDK to 1.7-rc1

- CMakeLists.txt
- appveyor.yml
- pmdk-convert.c
- tests/CMakeLists.txt
- tests/basic10.cmake
- tests/basic12.cmake
- tests/basic13.cmake
- tests/basic14.cmake
- tests/basic15.cmake
- tests/basic16.cmake
- tests/basic17.cmake
- tests/cli.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/79)
> Update PMDK to 1.8

- packages.cmake
- utils/docker/images/Dockerfile.fedora-28
- utils/docker/images/Dockerfile.ubuntu-18.04
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/87)
> Update contact info.

- tests/helpers.cmake
- tests/transaction.c
- tests/tx_intr_pool_regfile.cmake
- tests/tx_intr_poolset_local_2regfiles.cmake
- tests/tx_intr_poolset_local_2regfiles_rep_3regfiles.cmake
- tests/tx_intr_poolset_local_regfile.cmake
- tests/tx_intr_poolset_local_regfile_rep_regfile.cmake
including test case reordering to allow easy disabling of not common test cases
Ref: #80
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/83)
> test: disable scenarios 8 and 9 on PMDK version < 1.4

- CMakeLists.txt
- tests/CMakeLists.txt
- utils/docker/images/Dockerfile.fedora-28
- utils/docker/images/Dockerfile.ubuntu-18.04
Ref: issue#90
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-convert/91)
> common: fix dependency issue
